package com.flexicon.deck;

import jakarta.persistence.*;
import org.hibernate.annotations.CreationTimestamp;
import org.hibernate.annotations.DiscriminatorFormula;

import java.util.Date;
import java.util.List;

/**
 * An abstract deck superclass that contains all columns of a row in the deck table.
 * Each row contains the storage location and generation metadata of a deck file.
 *
 * @author isaac1000000
 */
@Entity
@Inheritance(strategy= InheritanceType.SINGLE_TABLE)
@Table(name="decks")
@DiscriminatorFormula("type")
public abstract class Deck<CardType extends Card> {

    /**
     * The unique id of the deck, autogenerated on the database side.
     */
    @Id
    @Column(name="id")
    @GeneratedValue
    private Long id;

    /**
     * The type of deck (ex: 'anki').
     */
    @Column(name="type")
    private String type;

    /**
     * The user-provided name for the deck. Optional.
     */
    @Column(name="name")
    private String name;

    /**
     * The extension for the exported deck file
     */
    @Column(name="ext")
    private String ext;

    /**
     * The mandatory and unique filepath for reaching the deck.
     */
    @Column(name="filepath")
    private String filepath;

    /**
     * The subject of the deck. Optional.
     */
    @Column(name="subject")
    private String subject;

    /**
     * The size (total number of elements) in the deck.
     */
    @Column(name="size")
    private int size;

    /**
     * The deck's date of creation.
     */
    @Column(name="createdAt")
    @CreationTimestamp
    private Date createdAt;

    /**
     * Creation metadata: the minimum acceptable target frequency value. Optional.
     */
    @Column(name="minFrequency")
    private Double minFrequency;

    /**
     * Creation metadata: the maximum acceptable target frequency value. Optional.
     */
    @Column(name="maxFrequency")
    private Double maxFrequency;

    /**
     * Creation metadata: the minimum acceptable relationship strength value. Optional.
     */
    @Column(name="minStrength")
    private Double minStrength;

    /**
     * Creation metadata: the maximum acceptable relationship strength value. Optional.
     */
    @Column(name="maxStrength")
    private Double maxStrength;

    /**
     * The list of cards that make up the deck.
     */
    @Transient
    private List<CardType> cardList;

    /**
     * A function to be implemented by subclasses that will create the file then internally store
     * filepath, file extension, and size.
     */
    public abstract void export();

    public Long getId() {
        return id;
    }

    public String getType() {
        return type;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getExt() {
        return ext;
    }

    public String getFilepath() {
        return filepath;
    }

    public String getSubject() {
        return subject;
    }

    public void setSubject(String subject) {
        this.subject = subject;
    }

    public int getSize() {
        return size;
    }

    public Date getCreatedAt() {
        return createdAt;
    }

    public Double getMinFrequency() {
        return minFrequency;
    }

    public void setMinFrequency(Double minFrequency) {
        this.minFrequency = minFrequency;
    }

    public Double getMaxFrequency() {
        return maxFrequency;
    }

    public void setMaxFrequency(Double maxFrequency) {
        this.maxFrequency = maxFrequency;
    }

    public Double getMinStrength() {
        return minStrength;
    }

    public void setMinStrength(Double minStrength) {
        this.minStrength = minStrength;
    }

    public Double getMaxStrength() {
        return maxStrength;
    }

    public void setMaxStrength(Double maxStrength) {
        this.maxStrength = maxStrength;
    }

    public List<CardType> getCardList() {
        return cardList;
    }

    public void addCard(CardType card) {
        cardList.add(card);
    }

    /**
     * Returns card at index <code>i</code>.
     *
     * @param i the index of the returned card
     * @return the card at index <code>i</code>
     */
    public CardType get(int i) {
        return cardList.get(i);
    }

    public Deck() {}
}
